language: java
before_script:
  - psql -c 'create database hex_repo_test;' -U postgres
  - cp hex_repo/test/hex_repo.properties{.sample,}
  - cp hex_repo/liquibase.properties{.example,}
before_install: ant ensure-ivy
before_script: ant -f hex_repo/build.xml prepare-test-data
branches:
  only:
    - master
jdk:
  - oraclejdk8
