language: java
before_script:
  - psql -c 'create database hex_repo_test;' -U postgres --port=5432
  - ant prepare
before_install: ant ensure-ivy
script:
  - ant test
branches:
  only:
    - master
jdk:
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
  - oraclejdk12
  - oraclejdk13
  - oraclejdk14
services:
  - postgresql
